package salsa.resources;

// Import declarations generated by the SALSA compiler, do not modify.
import java.io.IOException;
import java.util.Vector;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.InvocationTargetException;

import salsa.language.Actor;
import salsa.language.ActorReference;
import salsa.language.Message;
import salsa.language.RunTime;
import salsa.language.ServiceFactory;
// End SALSA compiler generated import delcarations.


public interface StorageService extends ActorReference {
	public interface State extends Actor {
		public  void store(Object object, String filename);
		public  Object get(String filename);
	}
}